### ISSUE TITLE
LED - Unterstützung benötigt

### ISSUE THREAD

**Issue by MDMAN** [alengwenus/lcn-frontend#40]
Ich habe in meiner ICL-Installation auch mehrere LED-Treiber die angesteuert werden müssen. Die einzelnen Ausgänge hängen immer an einem LCN-HL4 - Modul welches über ein LCN-SHS angesteuert wird.
Dahinter habe ich LED-Treiber die dann direkt auf den LED-Stripes aufgelegt sind. DIe LED-Stripes sind RGBW-Stripes. Haben also immer 4 Farben plus Dimmer und Sättigung. Zumindest kann ich das so in der LCN-Pro ablesen.

Ich benötige nun aber eine Möglichkeit, auch RGB und RGBW-LED-Stripes entsprechend ansteuern zu können und gleichzeitig die Farbgebung per RGB-Farbrad und einem Schieber für die Helligkeit /Dimmung und einen Schieber für die Sättigung/Farbstärke regeln zu können.

Ich habe mir das so vorgestellt, dass man diese Entitäten erst erstellen muss und diese dann in eine Art Helfer-Script zu einer LED-Leiste/LED-Stripe zusammenfassen kann und dort dann die Regler entsprechend belegen kann mit den einzelnen Entitäten.

Und dann sollte man auch in dem Dashboard von HA zum Beispiel diese LEDs als "einzelnes" Gerät einbinden können und dann ein Farbrad für die Farben und einen Regler für den Dimmer haben. In der MItte des Farbrades ist 0 also Sättigung = 0 und außen ist die Sättigung = 100% von dem Farbrad und drumherum sind dann die möglichen Farbkombinationen. So stelle ich mir das vor.

Wäre sowas programmierbar und umsetzbar? Dann könnte man auch die LEDs hinzufügen.

![LCN2](https://github.com/user-attachments/assets/01aed206-d7f3-40ff-8553-7c69f3be8bca)
![LCN12](https://github.com/user-attachments/assets/2854aff3-3b5c-4a45-bfb7-55fefb9a55a9)
![LCN13](https://github.com/user-attachments/assets/001a4e4b-da5e-49d9-9fb1-1cf7a66fe87e)
![LCN14](https://github.com/user-attachments/assets/0e52798f-b7e5-4254-966e-a8ddeb8467d0)

So stelle ich mir das vor:

<img width="492" alt="LED-RGBW-SKala" src="https://github.com/user-attachments/assets/69779563-2e2e-4598-a8db-774c9fcee846" />

Das wäre Top, wenn man sowas programmieren könnte.

**Comment by alengwenus** [comment]
Die Konfiguration aller möglichen existierenden LED-Typen und Farbschemata ist relativ komplex. Das Problem liegt dann nicht an der LCN Konfiguration, sondern an den "Spezialitäten" der einzelnen LED Treiber.
Ich denke, es ist besser, sich mit der [Template Light Platform](https://www.home-assistant.io/integrations/light.template/) zu behelfen. Damit kann man sich individuelle Lichter zusammenbasteln.
Voraussetzung ist, dass alle vier Ausgänge eines Moduls als Light-Entitäten (dimmbar!) in HA eingerichtet sind.

Dann könnte ein Eintrag für ein RGBW-Licht, das vier Ausgänge ansteuert (`light.light_output1` bis `light.light_output4` ) in der `configuration.yaml` so ausssehen:

```yaml
light:
  - platform: template
    lights:
     rgbw_light:
      friendly_name: "RGBW Light"
      rgbw_template: (
        {{ state_attr('light.light_output1', 'brightness')|d(0, true) }},
        {{ state_attr('light.light_output2', 'brightness')|d(0, true) }},
        {{ state_attr('light.light_output3', 'brightness')|d(0, true) }},
        {{ state_attr('light.light_output4', 'brightness')|d(0, true) }}
        )
      level_template: "{{ (state_attr('light.light_output1', 'brightness')|d(0, true) + state_attr('light.light_output2', 'brightness')|d(0, true) + state_attr('light.light_output3', 'brightness')|d(0, true) + state_attr('light.light_output4', 'brightness')|d(0, true))/4 }}"
      value_template: "{{ (state_attr('light.light_output1', 'brightness')|d(0, true) + state_attr('light.light_output2', 'brightness')|d(0, true) + state_attr('light.light_output3', 'brightness')|d(0, true) + state_attr('light.light_output4', 'brightness')|d(0, true)) > 0 }}"
      availability_template: "{{ not is_state('light.light_output1', 'unavailable') and not is_state('light.light_output2', 'unavailable') and not is_state('light.light_output3', 'unavailable') and not is_state('light.light_output4', 'unavailable') }}"
      supports_transition_template: true
      turn_on:
        - if:
          - condition: not
            conditions:
              - condition: template
                value_template: "{{ states.scene.rgbw_snapshot.state != None }}"
          then:
            - action: light.turn_on
              entity_id: light.light_output1, light.light_output2, light.light_output3, light.light_output4
              data:
                transition: 0
          else:
            - action: scene.turn_on
              target:
                entity_id: scene.rgbw_snapshot
      turn_off:
        sequence:
          - action: scene.create
            data:
              scene_id: rgbw_snapshot
              snapshot_entities: light.light_output1, light.light_output2, light.light_output3, light.light_output4
          - action: light.turn_off
            entity_id: light.light_output1, light.light_output2, light.light_output3, light.light_output4
            data:
              transition: 0
      set_level:
        action: light.turn_on
        entity_id: light.light_output1, light.light_output2, light.light_output3, light.light_output4
        data:
          brightness: "{{ brightness }}"
          transition: 0
      set_rgbw:
        parallel:
          - action: light.turn_on
            entity_id: light.light_output1
            data:
              brightness: "{{ r }}"
              transition: 0
          - action: light.turn_on
            entity_id: light.light_output2
            data:
              brightness: "{{ g }}"
              transition: 0
          - action: light.turn_on
            entity_id: light.light_output3
            data:
              brightness: "{{ b }}"
              transition: 0
          - action: light.turn_on
            entity_id: light.light_output4
            data:
              brightness: "{{ w }}"
              transition: 0
```

Das sieht dann so aus:

![image](https://github.com/user-attachments/assets/cc608d95-bba0-4019-945c-c86967cec919)

**Comment by MDMAN** [comment]
Ja das wäre doch super... Sieht ja fast genauso aus wie ich mir des vorgestellt hatte.
ABER: Wie kann ich das denn bitte in meine Installation einbinden? Wie muss ich das anstellen?
Leider habe ich noch nicht so die Erfahrung mit eigenen "Skripten" in der YAML-Datei... 

Wie kann ich denn dort einen LED-Stripe entsprechend zuweisen?

**Comment by krismarc** [comment]
@alengwenus nice, I've build similar thing myself long time back, but it doesn't work perfectly fine.

I'll try your sample, thx!

```
light:
  - platform: template
    lights:
      kwadrat_kuchnia_rgbw:
        friendly_name: "kwadrat_kuchnia_rgbw"
        turn_on:
          - service: light.turn_on
            entity_id: light.kwadrat_kuchnia_white
          - service: light.turn_off
            entity_id: light.kwadrat_kuchnia_red, light.kwadrat_kuchnia_green, light.kwadrat_kuchnia_blue
        turn_off:
          service: light.turn_off
          entity_id: light.kwadrat_kuchnia_white, light.kwadrat_kuchnia_red, light.kwadrat_kuchnia_green, light.kwadrat_kuchnia_blue
        set_level:
          service: light.turn_on
          entity_id: light.kwadrat_kuchnia_white
          data:
            brightness: "{{ brightness }}"
        set_rgbw:
          service: script.kwadrat_kuchnia_set_rgbw
          data:
            r: "{{r}}"
            g: "{{g}}"
            b: "{{b}}"
            w: "{{w}}"
      kwadrat_jadalnia_rgbw:
        friendly_name: "kwadrat_jadalnia_rgbw"
        turn_on:
          - service: light.turn_on
            entity_id: light.kwadrat_jadalnia_white
          - service: light.turn_off
            entity_id: light.kwadrat_jadalnia_red, light.kwadrat_jadalnia_green, light.kwadrat_jadalnia_blue
        turn_off:
          service: light.turn_off
          entity_id: light.kwadrat_jadalnia_white, light.kwadrat_jadalnia_red, light.kwadrat_jadalnia_green, light.kwadrat_jadalnia_blue
        set_level:
          service: light.turn_on
          entity_id: light.kwadrat_jadalnia_white
          data:
            brightness: "{{ brightness }}"
        set_rgbw:
          service: script.kwadrat_jadalnia_set_rgbw
          data:
            r: "{{r}}"
            g: "{{g}}"
            b: "{{b}}"
            w: "{{w}}"
      kwadrat_salon_rgbw:
        friendly_name: "kwadrat_salon_rgbw"
        turn_on:
          - service: light.turn_on
            entity_id: light.kwadrat_salon_white
          - service: light.turn_off
            entity_id: light.kwadrat_salon_red, light.kwadrat_salon_green, light.kwadrat_salon_blue
        turn_off:
          service: light.turn_off
          entity_id: light.kwadrat_salon_white, light.kwadrat_salon_red, light.kwadrat_salon_green, light.kwadrat_salon_blue
        set_level:
          service: light.turn_on
          entity_id: light.kwadrat_salon_white
          data:
            brightness: "{{ brightness }}"
        set_rgbw:
          service: script.kwadrat_salon_set_rgbw
          data:
            r: "{{r}}"
            g: "{{g}}"
            b: "{{b}}"
            w: "{{w}}"
      kwadraty_wszystkie_rgbw:
        friendly_name: "kwadraty_wszystkie_rgbw"
        turn_on:
          - service: light.turn_on
            entity_id: light.kwadrat_kuchnia_white, light.kwadrat_jadalnia_white, light.kwadrat_salon_white
          - service: light.turn_off
            entity_id: light.kwadrat_kuchnia_red, light.kwadrat_kuchnia_green, light.kwadrat_kuchnia_blue, light.kwadrat_jadalnia_red, light.kwadrat_jadalnia_green, light.kwadrat_jadalnia_blue, light.kwadrat_salon_red, light.kwadrat_salon_green, light.kwadrat_salon_blue
        turn_off: 
          service: light.turn_off
          entity_id: light.kwadrat_kuchnia_white, light.kwadrat_kuchnia_red, light.kwadrat_kuchnia_green, light.kwadrat_kuchnia_blue, light.kwadrat_jadalnia_white, light.kwadrat_jadalnia_red, light.kwadrat_jadalnia_green, light.kwadrat_jadalnia_blue, light.kwadrat_salon_white, light.kwadrat_salon_red, light.kwadrat_salon_green, light.kwadrat_salon_blue
        set_level:
          service: light.turn_on
          entity_id: light.kwadrat_kuchnia_white, light.kwadrat_jadalnia_white, light.kwadrat_salon_white
          data:
            brightness: "{{ brightness }}"
        set_rgbw:
          service: script.kwadraty_wszystkie_set_rgbw
          data:
            r: "{{r}}"
            g: "{{g}}"
            b: "{{b}}"
            w: "{{w}}"
```

script content:|
```
sequence:
  - data:
      entity_id: light.kwadrat_jadalnia_red
      brightness: "{{r}}"
    action: light.turn_on
  - data:
      entity_id: light.kwadrat_jadalnia_green
      brightness: "{{g}}"
    action: light.turn_on
  - data:
      entity_id: light.kwadrat_jadalnia_blue
      brightness: "{{b}}"
    action: light.turn_on
  - data:
      entity_id: light.kwadrat_jadalnia_white
      brightness: "{{w}}"
    action: light.turn_on
alias: kwadrat_jadalnia_set_rgbw
mode: single

```
